### PR TITLE
Fix and reorder translations

### PR DESCRIPTION
**Pull request by GeorgeLimaDev**
#### What problem is this solving?

It relates to the task [LOC-14868](https://vtex-dev.atlassian.net/browse/LOC-14868). The Localization team found some incorrect translations. And as they were fixed, we also took the chance to reorder the keys in alphabetical order, so their maintainability will be inproved for the next PRs.

[LOC-14868]: https://vtex-dev.atlassian.net/browse/LOC-14868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sheilagomes — APPROVED** [review]
LGTM

**Comment by ArthurTriis1** [comment]
LGTM! Can you fix the conflicts?

**Comment by GeorgeLimaDev** [comment]
> LGTM! Can you fix the conflicts?
@ArthurTriis1, done! Do you prefer to go on with merge and deploy or can I do it?

**Comment by ArthurTriis1** [comment]
> > LGTM! Can you fix the conflicts?
> > @ArthurTriis1, done! Do you prefer to go on with merge and deploy or can I do it?

Im doing, thanks!

**Pull request merged**
